/*auth*/
const AUTH={
  CHANGE_USERDATA: "CHANGE_USERDATA",

  CHECK_USERNAME: "CHECK_USERNAME",
  CHECK_NICKNAME: "CHECK_NICKNAME",
  CHANGE_CHECK: 'CHANGE_CHECK',

  AUTHDATA_RESET: 'AUTHDATA_RESET',

  SET_SUBMIT_STATUS: 'SET_SUBMIT_STATUS',
  SET_ERRORMESSAGE: "SET_ERRORMESSAGE",

  SIGNUP: "SIGNUP",
  SIGNIN: "SIGNIN",

  CHECK_SESSION: "CHECK_SESSION",

  LOGOUT: "LOGOUT"
};

export default AUTH;
