/*auth*/
const AUTH={
  CHECK_SESSION: "CHECK_SESSION",
  GET_HISTORY:"GET_HISTORY",

  CHANGE_USERDATA: "CHANGE_USERDATA",

  RECOMMEND_FOLLOW: "RECOMMEND_FOLLOW",

  SET_FOLLOW_USER: "SET_FOLLOW_USER",

  FOLLOWING: "FOLLOWING",
  UNFOLLOW: "UNFOLLOW",

  LOGOUT: "LOGOUT"
};

export default AUTH;
