const FORM={
  POSTFORM_RESET:"POSTFORM_RESET",
  SET_POST_MEDIA_RESET:"SET_POST_MEDIA_RESET",

  SET_POST_MEDIA:"SET_POST_MEDIA",
  MOVE_MEDIA: "MOVE_MEDIA",
  DELETE_MEDIA: "DELETE_MEDIA",

  CHANGE_FORMDATA: "CHANGE_FORMDATA",

  CHECK_USERNAME: "CHECK_USERNAME",
  CHECK_NICKNAME: "CHECK_NICKNAME",
  CHANGE_CHECK: 'CHANGE_CHECK',

  FORMDATA_RESET: 'FORMDATA_RESET',

  SET_SUBMIT_STATUS: 'SET_SUBMIT_STATUS',
  SET_ERRORMESSAGE: "SET_ERRORMESSAGE",

  SIGNUP: "SIGNUP",
  SIGNIN: "SIGNIN",
}

export default FORM;
