const FORM={
  POSTFORM_RESET:"POSTFORM_RESET",
  SET_POST_CONTENT:"SET_POST_CONTENT",

  SET_POST_MEDIA_RESET:"SET_POST_MEDIA_RESET",

  SET_POST_MEDIA:"SET_POST_MEDIA",
  MOVE_MEDIA: "MOVE_MEDIA",
  DELETE_MEDIA: "DELETE_MEDIA"
}

export default FORM;
