const POST={
  SEARCH_POSTS: "SEARCH_POSTS",
  SEARCH_REPLY: "SEARCH_REPLY",
  SEARCH_ALLREPALY: "SEARCH_ALLREPALY",
  SEARCH_LIKE: "SEARCH_LIKE",

  SET_POST_INDEX: "SET_POST_INDEX",
  LIKE_ATC: "LIKE_ATC",
  NOTLIKE_ATC: "NOTLIKE_ATC",

  INSERT_REPLY: "INSERT_REPLY",
  DELETE_REPLY: "DELETE_REPLY",

  GET_ALL_REPLIES: "GET_ALL_REPLIES",
  SET_MODAL:"SET_MODAL",

  SET_POST_CONTENT:"SET_POST_CONTENT",
  SET_POST_MEDIA:"SET_POST_MEDIA"
}

export default POST;
