const POSTFRM={
  SET_POST_CONTENT:"SET_POST_CONTENT",

  SET_POST_MEDIA_RESET:"SET_POST_MEDIA_RESET",

  SET_POST_MEDIA:"SET_POST_MEDIA",
  MOVE_MEDIA: "MOVE_MEDIA",
  TOGGLE_DRAGGING: "TOGGLE_DRAGGING"
}

export default POSTFRM;
