const POST={
  POSTS_RESET: "POSTS_RESET",
  SEARCH_POSTS: "SEARCH_POSTS",
  DELETE_POST: "DELETE_POST",

  SET_POST_INDEX: "SET_POST_INDEX",
  LIKE_ATC: "LIKE_ATC",
  NOTLIKE_ATC: "NOTLIKE_ATC",

  INSERT_REPLY: "INSERT_REPLY",
  DELETE_REPLY: "DELETE_REPLY",

  GET_ALL_REPLIES: "GET_ALL_REPLIES",
  SET_MODAL:"SET_MODAL",

  UPLOAD_POST:"UPLOAD_POST"
}

export default POST;
