const POST={
  POSTS_RESET: "POSTS_RESET",
  SEARCH_POSTS: "SEARCH_POSTS",
  DELETE_POST: "DELETE_POST",

  SET_MEDIA_INDEX: "SET_MEDIA_INDEX",
  SET_MEDIA_PLAY: "SET_MEDIA_PLAY",
  SET_POST_REPLY: "SET_POST_REPLY",

  SET_POST_INDEX: "SET_POST_INDEX",
  LIKE_ATC: "LIKE_ATC",
  NOTLIKE_ATC: "NOTLIKE_ATC",

  INSERT_REPLY: "INSERT_REPLY",
  DELETE_REPLY: "DELETE_REPLY",

  GET_ALL_REPLIES: "GET_ALL_REPLIES",
  SET_MODAL:"SET_MODAL",

  UPLOAD_POST:"UPLOAD_POST",

  GET_POST_DETAIL_INFO:"GET_POST_DETAIL_INFO",
  GET_POST_DETAIL_REPLIES:"GET_POST_DETAIL_REPLIES",

  POST_DETAIL_LIKE: "POST_DETAIL_LIKE",
  POST_DETAIL_NOTLIKE: "POST_DETAIL_NOTLIKE",

  POST_DETAIL_INSERT_REPLY: "POST_DETAIL_INSERT_REPLY",
  POST_DETAIL_DELETE_REPLY: "POST_DETAIL_DELETE_REPLY",
}

export default POST;
