const SEARCH={
  SEARCH_HASH:"SEARCH_HASH",
  ADD_HASH:"ADD_HASH",

  SET_MODAL_POST_INDEX:"SET_MODAL_POST_INDEX",

  GET_MODAL_POST:"GET_MODAL_POST",

  SET_MODAL_INIT:"SET_MODAL_INIT",

  MODAL_POST_LIKE:"MODAL_POST_LIKE",
  MODAL_POST_NOTLIKE:"MODAL_POST_NOTLIKE"
}
export default SEARCH;
