const SEARCH={
  SEARCH_HASH:"SEARCH_HASH",
  ADD_HASH:"ADD_HASH",

  SEARCH_USER:"SEARCH_USER",
  ADD_USER_POST:"ADD_USER_POST",

  SET_MODAL_POST_INDEX:"SET_MODAL_POST_INDEX",

  GET_MODAL_POST:"GET_MODAL_POST",

  SET_MODAL_INIT:"SET_MODAL_INIT",

  MODAL_POST_LIKE:"MODAL_POST_LIKE",
  MODAL_POST_NOTLIKE:"MODAL_POST_NOTLIKE",

  MODAL_POST_INSERT_REPLY:"MODAL_POST_INSERT_REPLY",
  MODAL_POST_DELETE_REPLY:"MODAL_POST_DELETE_REPLY",
  MODAL_POST_GET_ALL_REPLIES:"MODAL_POST_GET_ALL_REPLIES",

  SET_INNER_MODAL:"SET_INNER_MODAL",

  GET_USER_FOLLOWER: "GET_USER_FOLLOWER",
  GET_USER_FOLLOWING: "GET_USER_FOLLOWING",

  DELETE_MODAL_POST: "DELETE_MODAL_POST",

  CHANGE_MODAL_INFO: "CHANGE_MODAL_INFO"
}
export default SEARCH;
