const UI={
  SET_HEADER:"SET_HEADER",
  SET_HEADER_MODAL:"SET_HEADER_MODAL",
  SET_LOADING_INITIAL:"SET_LOADING_INITIAL",
  SET_LOADING:"SET_LOADING",

  SET_MYPAGE_MODAL:"SET_MYPAGE_MODAL"
}
export default UI;
