const UI={
  SET_HEADER:"SET_HEADER",
  SET_HEADER_MODAL:"SET_HEADER_MODAL",
  SET_LOADING_INITIAL:"SET_LOADING_INITIAL",
  SET_LOADING:"SET_LOADING",

  SET_UI_MODAL:"SET_UI_MODAL",
  SET_FOLLOW_MODAL_INITIAL:"SET_FOLLOW_MODAL_INITIAL"
}
export default UI;
